apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodhi-user-system
  namespace: apps
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bodhi-user-system
  template:
    metadata:
      labels:
        app: bodhi-user-system
    spec:
      nodeSelector:
        nodegroup: "int"
        topology.kubernetes.io/zone: "ap-southeast-1a"
      containers:
        - name: bodhi-user-system
          ports:
            - name: supplement
              protocol: TCP
              containerPort: 5432
          image: 476114114107.dkr.ecr.ap-southeast-1.amazonaws.com/bodhi-user-system:0.0.3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bodhi-user-system
  namespace: apps
spec:
  type: LoadBalancer
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: bodhi-user-system