apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodhi-user-system
  namespace: apps
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bodhi-user-system
  template:
    metadata:
      labels:
        app: bodhi-user-system
    spec:
      nodeSelector:
        nodegroup: "int"
        topology.kubernetes.io/zone: "ap-southeast-1a"
      containers:
        - name: bodhi-user-system
          ports:
            - name: supplement
              protocol: TCP
              containerPort: 8082
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
          image: 476114114107.dkr.ecr.ap-southeast-1.amazonaws.com/bodhi-user-system:0.0.8 # {"$imagepolicy": "flux-system:bodhi-user-system-policy"}
          env:
            - name: DATABASE_URL
              value: "postgres://bodhiint:bodhiint@a18724c4706444438a4ee795db222af7-118215569.ap-southeast-1.elb.amazonaws.com:5432/app?sslmode=disable"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bodhi-user-system
  namespace: apps
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: bodhi-user-system
  