apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodhi-frontend
  namespace: apps
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: bodhi-frontend
  template:
    metadata:
      labels:
        app: bodhi-frontend
    spec:
      nodeSelector:
        nodegroup: "int"
        topology.kubernetes.io/zone: "ap-southeast-1a"
      containers:
        - name: bodhi-frontend
          ports:
            - name: supplement
              protocol: TCP
              containerPort: 8087
          livenessProbe:
            httpGet:
              path: /
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
          image: 476114114107.dkr.ecr.ap-southeast-1.amazonaws.com/bodhi_frontend:0.0.7 # {"$imagepolicy": "flux-system:bodhi-frontend-policy"}
          env:
            - name: VUE_APP_URL_AUTHENTICATION
              value: http://a2969fb695db944018dc5dbf99f767b6-767196914.ap-southeast-1.elb.amazonaws.com:8082
            - name: VUE_APP_URL_FILE_SYSTEM
              value: http://a3d98f973bfef4185bb2f7b8bfdfaa83-495409922.ap-southeast-1.elb.amazonaws.com:9377
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 400m
              memory: 800Mi
---
apiVersion: v1
kind: Service
metadata:
  name: bodhi-frontend
  namespace: apps
spec:
  type: LoadBalancer
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: bodhi-frontend
  